# Generated by Django 4.0 on 2021-12-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carbrand',
            name='model',
        ),
        migrations.AddField(
            model_name='carbrand',
            name='model',
            field=models.ManyToManyField(to='api.CarModel'),
        ),
    ]
