# Generated by Django 4.0 on 2021-12-23 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_carbrand_model_carbrand_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='carbrand',
            name='model',
        ),
        migrations.AddField(
            model_name='carmodel',
            name='car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.carbrand'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='power',
            field=models.CharField(choices=[('Internal Combustion Engine', 'Internal Combustion Engine'), ('Electric Drive', 'Electric Drive'), ('Hybrid Drive', 'Hybrid Drive')], max_length=50),
        ),
        migrations.CreateModel(
            name='BookDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=200)),
                ('bok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rbook', to='api.book')),
            ],
        ),
    ]
