# Generated by Django 4.0 on 2021-12-23 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_book_remove_carbrand_model_carmodel_car_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rcar', to='api.carbrand'),
        ),
    ]
