# Generated by Django 4.0 on 2021-12-23 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_carmodel_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookdetails',
            name='bok',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookDetails',
        ),
    ]
