# Generated by Django 4.0 on 2021-12-23 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_bookdetails_bok_delete_book_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('latitude', models.CharField(max_length=50)),
                ('longitude', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=50)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='api.carmodel')),
            ],
        ),
    ]
