# Generated by Django 4.0 on 2021-12-23 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_carvendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model', to='api.carbrand'),
        ),
    ]
