# Generated by Django 4.0 on 2022-01-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tastie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplerest',
            name='data',
            field=models.JSONField(default='a'),
            preserve_default=False,
        ),
    ]
