# Generated by Django 4.0 on 2021-12-24 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WebhookData',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('reference', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.CharField(blank=True, max_length=50, null=True)),
                ('gateway_response', models.CharField(blank=True, max_length=50, null=True)),
                ('paid_at', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.CharField(blank=True, max_length=50, null=True)),
                ('channel', models.CharField(blank=True, max_length=50, null=True)),
                ('currency', models.CharField(blank=True, max_length=50, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True)),
                ('metadata', models.CharField(blank=True, max_length=50, null=True)),
                ('log', models.CharField(blank=True, max_length=50, null=True)),
                ('fees', models.CharField(blank=True, max_length=50, null=True)),
                ('customer', models.CharField(blank=True, max_length=50, null=True)),
                ('authorization', models.CharField(blank=True, max_length=50, null=True)),
                ('plan', models.CharField(blank=True, max_length=50, null=True)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='dj_paystack.webhook')),
            ],
        ),
    ]
