# Generated by Django 4.0 on 2021-12-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_paystack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookdata',
            name='domian',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
