# Generated by Django 4.0 on 2022-01-06 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dj_paystack', '0002_webhookdata_domian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookdata',
            name='data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='dj_paystack.webhook'),
        ),
    ]
