# Generated by Django 4.0 on 2022-01-06 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dj_paystack', '0003_alter_webhookdata_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webhookdata',
            name='log',
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_spent', models.PositiveIntegerField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(blank=True, null=True)),
                ('authentication', models.CharField(blank=True, max_length=50, null=True)),
                ('errors', models.PositiveIntegerField(blank=True, null=True)),
                ('success', models.BooleanField(blank=True, null=True)),
                ('mobile', models.BooleanField(blank=True, null=True)),
                ('input', models.CharField(blank=True, max_length=50, null=True)),
                ('channel', models.CharField(blank=True, max_length=50, null=True)),
                ('history', models.CharField(blank=True, max_length=50, null=True)),
                ('log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='log', to='dj_paystack.webhookdata')),
            ],
        ),
    ]
