# Generated by Django 4.0 on 2022-01-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_paystack', '0004_remove_webhookdata_log_webhooklog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webhooklog',
            name='input',
        ),
        migrations.CreateModel(
            name='WebhookInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.ManyToManyField(related_name='input', to='dj_paystack.WebhookLog')),
            ],
        ),
    ]
