# Generated by Django 4.0 on 2022-01-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_paystack', '0005_remove_webhooklog_input_webhookinput'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webhooklog',
            name='history',
        ),
        migrations.CreateModel(
            name='WebhookHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.CharField(blank=True, max_length=250, null=True)),
                ('time', models.PositiveIntegerField(blank=True, null=True)),
                ('input', models.ManyToManyField(related_name='history', to='dj_paystack.WebhookLog')),
            ],
        ),
    ]
