# Generated by Django 4.0 on 2022-01-06 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dj_paystack', '0006_remove_webhooklog_history_webhookhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webhookhistory',
            old_name='input',
            new_name='history',
        ),
    ]
