# Generated by Django 4.0 on 2022-01-06 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dj_paystack', '0007_rename_input_webhookhistory_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webhookhistory',
            old_name='type',
            new_name='tpe',
        ),
    ]
