# Generated by Django 4.0 on 2022-01-06 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dj_paystack', '0009_rename_tpe_webhookhistory_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webhookhistory',
            name='history',
        ),
        migrations.AddField(
            model_name='webhookhistory',
            name='history',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='dj_paystack.webhooklog'),
            preserve_default=False,
        ),
    ]
