# Generated by Django 4.0 on 2022-01-06 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dj_paystack', '0011_remove_webhookdata_customer_webhookcustomer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webhookdata',
            name='authorization',
        ),
        migrations.CreateModel(
            name='WebhookAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorization_code', models.CharField(blank=True, max_length=50, null=True)),
                ('bin', models.CharField(blank=True, max_length=50, null=True)),
                ('last4', models.CharField(blank=True, max_length=50, null=True)),
                ('exp_month', models.CharField(blank=True, max_length=50, null=True)),
                ('exp_year', models.CharField(blank=True, max_length=50, null=True)),
                ('card_type', models.CharField(blank=True, max_length=50, null=True)),
                ('bank', models.CharField(blank=True, max_length=50, null=True)),
                ('country_code', models.CharField(blank=True, max_length=50, null=True)),
                ('brand', models.CharField(blank=True, max_length=50, null=True)),
                ('account_name', models.CharField(blank=True, max_length=50, null=True)),
                ('authorization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='authorization', to='dj_paystack.webhookdata')),
            ],
        ),
    ]
