# Generated by Django 4.0 on 2022-01-06 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dj_paystack', '0012_remove_webhookdata_authorization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webhookdata',
            name='plan',
        ),
        migrations.CreateModel(
            name='WebhookPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='dj_paystack.webhookdata')),
            ],
        ),
    ]
